sudo: required
services:
  - docker

before_install:
  - docker build -t jctiru/docker-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true jctiru/docker-cicd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-cicd"
  env: "DockerCicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-839624972951"
  bucket_path: "docker-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
